# Generated by Django 5.2.7 on 2025-10-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-hired_on'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='staff',
            name='can_approve_loans',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_approve_savings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='Staff', max_length=128),
        ),
    ]
