# Generated by Django 5.2.7 on 2025-10-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_at',
            new_name='joined_on',
        ),
        migrations.AlterField(
            model_name='member',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
