# Generated by Django 5.2.7 on 2025-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_joined_at_member_joined_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
